config/routes.rb
PizzariaWebApp::Application.routes.draw do
  devise_for :admins

  devise_for :users

  resources :orders do
    delete :destroy_all, :on => :collection
  end

  root :to => 'orders#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :customer_name, :pizzas_attributes 
  has_many :pizzas
  accepts_nested_attributes_for :pizzas, :allow_destroy => true
end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
  attr_accessible :order, :size, :toppings 
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_admin_or_user, :except => :index
  before_filter :authenticate_admin!, :only => [ :edit, :update, :destroy ]

  def authenticate_admin_or_user
    is_logged_in = self.admin_signed_in? || self.user_signed_in?
    unless is_logged_in
      flash[:notice] = "Must be logged in"
      redirect_to orders_url
    end
    is_logged_in
  end
  def index
    @orders = Order.all

    respond_to do |format|
      format.html
      format.json { render :json => @orders }
    end
  end
  def new
    @order = Order.new
    @order.pizzas.build
    @toppings_array = []

    respond_to do |format|
      format.html
      format.json { render :json => @order }
    end
  end
  def create
    ingredients = params[:ingredients]
    ingredients_string = ingredients.join ' '
    params[:order][:pizzas_attributes]["0"][:toppings] = ingredients_string
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to orders_url, :notice => "Order successfully created" }
        format.json { render :json => @order, :status => :created, :location => @order }
      end
    end
  end
  def edit
    @order = Order.find(params[:id])
    @toppings_array = @order.pizzas.first.toppings.split ' '

    respond_to do | format|
      format.html
      format.json { render :json => @order }
    end
  end
  def update
    ingredients = params[:ingredients]
    ingredients_string = ingredients.join ' '
    params[:order][:pizzas_attributes]["0"][:toppings] = ingredients_string
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to orders_url, :notice => "Order successfully updated" }
        format.json { render :json => @order, :status => :created, :location => @order }
      end
    end
  end
  def destroy
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.destroy
        format.html { redirect_to orders_url, :notice => "Order successfully deleted" }
      end
    end
  end
  def destroy_all
    orders = Order.all
    orders.each do |order|
      order.destroy
    end
    flash[:notice] = "All orders deleted"
    redirect_to orders_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
  def pizza_sizes
    # displays "Small" but saves "s"
    [ ["Small", "s"], ["Medium", "m"], ["Large", "l"], ["X-Large", "x"] ]
  end
  def pizza_size_display size
    size_array = pizza_sizes.find { |s| s[1] == size }
    size_array ? size_array[0] : "undefined"
  end
  def pizza_ingredients
    [ "Pepperoni", "Sausage", "Onion", "Bacon"]
  end
  def pizza_ingredients_to_array ingredients
    ingredients.split ' '
  end
  def pizza_ingredients_to_string ingredients
    ingredients.join ' '
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PizzariaWebApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |form| %>
  <div class="field">
    <%= form.label :customer_name %><br />
    <%= form.text_field :customer_name %>
  </div>
  <%= form.fields_for :pizzas do |builder| %>
    <div class="field">
      <%= builder.label :size %> <br />
      <%= builder.select :size, pizza_sizes %>
    </div>
    <% pizza_ingredients.each do |ingredient| %>
      <div class="field">
        <%= builder.label ingredient %> <br />
        <%= check_box_tag "ingredients[]", ingredient, @toppings_array.include?(ingredient) %>
      </div>
    <% end %>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>
<p id="notice"><%= notice %></p>
<table>
  <th> Customer Name </th>
  <th> Pizza Size </th>
  <th> Toppings </th>
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.customer_name %> </td>
      <td><%= pizza_size_display(order.pizzas.first.size) %> </td>
      <td><%= order.pizzas.first.toppings %> </td>
      <% if admin_signed_in? %>
        <td><%= link_to 'Edit order', edit_order_path(order) %>
        <td><%= link_to 'Delete order', order_path(order), :confirm => "Are you sure?", :method => :delete %>
      <% end %>
    </tr>
  <% end %>
  </table>
  <br />
  <%= link_to 'New order', new_order_path %>
  <% if user_signed_in? && !admin_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  <% elsif !admin_signed_in? %>
    <%= link_to('Login', new_user_session_path)  %>
  <% end %>
  <% if admin_signed_in? %>
    <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>
  <% end %>
  <%= link_to('Delete all', destroy_all_orders_path, :method => :delete) %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= form_for(@order) do |form| %>
  <div class="field">
    <%= form.label :customer_name %><br />
    <%= form.text_field :customer_name %>
  </div>
  <%= form.fields_for :pizzas do |builder| %>
    <div class="field">
      <%= builder.label :size %> <br />
      <%= builder.text_field :size %>
    </div>
    <div class="field">
      <%= builder.label :toppings %> <br />
      <%= builder.text_area :toppings %>
    </div>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', orders_path %>